### ISSUE TITLE
请问这个项目有部署方法吗？

### ISSUE THREAD

**Issue by qingyuan0o0** [linweiyuan/next-chatgpt#3]
这个项目我使用npm run dev没有运行成功哈，不知道是不是方法不对？

**Comment by linweiyuan** [comment]
看下什么错误

**Comment by qingyuan523** [comment]
用repl.it部署的，运行后内存超过1G就被kill了

**Comment by linweiyuan** [comment]
你们是同一个人吗

能跑起来，还是跑都跑不起来？

这个项目只是一个练手的，一堆 bug，并不适合使用

**Comment by qingyuan523** [comment]
明白了😊👌，之前你api在潘多拉可用，后来就不行了能否想办法支持热更新？

**Comment by linweiyuan** [comment]
好久没关注了，现在不兼容提示什么

**Comment by qingyuan523** [comment]
左边对话历史不加载，并且没办法正常交互，登录没有问题，账户显示没有问题

**Comment by linweiyuan** [comment]
api 日志显示什么

这个 api 只兼容官方的链接和结构，比如对话是 /conversations，如果整个 /abc，那么就不兼容

这个问题，不是很愿意去主动适配

**Comment by qingyuan523** [comment]
所以我才想说试试当前项目是否可用😅

**Comment by linweiyuan** [comment]
好多专业的前端项目

api 那个项目的文档拉到最下面

**Comment by qingyuan523** [comment]
好的谢谢

**Comment by qingyuan0o0** [comment]
![image](https://github.com/linweiyuan/next-chatgpt/assets/18437931/b1fd980f-d43a-4827-b71b-dbeb689ab808)
![image](https://github.com/linweiyuan/next-chatgpt/assets/18437931/397e0de6-2065-459c-acfd-5e0c86a5583c)

**Comment by linweiyuan** [comment]
你们不是同一个人？

看上面回复，别用这个，用别的专业的
